version: '3'
services:
  node:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/scr/app
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3307"
    volumes:
      - mysqlBanco:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "primeiraTabela"
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:


volumes:
  mysqlBanco:
